export type AnalyticsEventName =
  | 'page_view'
  | 'home_view'
  | 'doctor_page_view'
  | 'services_page_view'
  | 'service_card_click'
  | 'service_view'
  | 'service_booking_click'
  | 'service_whatsapp_click'
  | 'service_phone_click'
  | 'service_faq_expand'
  | 'related_service_click'
  | 'technology_page_view'
  | 'technology_detail_view'
  | 'technology_service_click'
  | 'technology_doctor_click'
  | 'technology_location_click'
  | 'technology_faq_expand'
  | 'technology_booking_click'
  | 'technology_whatsapp_click'
  | 'technology_phone_click'
  | 'cases_page_view'
  | 'case_view'
  | 'case_filter_used'
  | 'case_card_click'
  | 'case_gallery_open'
  | 'case_booking_click'
  | 'case_whatsapp_click'
  | 'case_phone_click'
  | 'location_page_view'
  | 'location_directions_click'
  | 'location_phone_click'
  | 'location_whatsapp_click'
  | 'location_booking_click'
  | 'blog_page_view'
  | 'article_view'
  | 'article_category_filter'
  | 'article_search'
  | 'article_share'
  | 'article_related_service_click'
  | 'article_booking_click'
  | 'article_whatsapp_click'
  | 'article_phone_click'
  | 'contact_page_view'
  | 'contact_form_start'
  | 'contact_form_submit'
  | 'consultation_cta_click'
  | 'whatsapp_click'
  | 'phone_click'
  | 'directions_click'
  | 'booking_flow_start'
  | 'booking_flow_complete'
  | 'view_service'
  | 'view_doctor'
  | 'view_location'
  | 'doctor_preview_click'
  | 'doctor_booking_click'
  | 'doctor_whatsapp_click'
  | 'doctor_phone_click'
  | 'doctor_service_click'
  | 'doctor_technology_click'
  | 'doctor_location_click'
  | 'service_preview_click'
  | 'technology_preview_click'
  | 'case_preview_click'
  | 'location_click'
  | 'article_preview_click'
  | 'click_whatsapp'
  | 'click_phone'
  | 'booking_start'
  | 'lead'
  | 'contact_submit';

export interface AnalyticsEventParams {
  category?: string;
  label?: string;
  value?: number;
  location_name?: string;
  location_id?: string;
  location_slug?: string;
  article_slug?: string;
  article_id?: string;
  article_category?: string;
  search_query?: string;
  share_platform?: string;
  service_name?: string;
  technology_name?: string;
  case_slug?: string;
  case_id?: string;
  case_category?: string;
  cta_location?: string;
  faq_question?: string;
  [key: string]: unknown;
}

export interface AnalyticsConfig {
  gaMeasurementId?: string;
  metaPixelId?: string;
  enabled?: boolean;
  debug?: boolean;
}
